# Uncomment the lines below you want to change by removing the # in the beginning

# App Store 요구 해상도에 맞는 시뮬레이터 (설치된 기기만)
# 1320×2868, 1290×2796 (iPhone) / 2048×2732, 2064×2752 (iPad)
devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Plus",
  "iPhone 13 Pro Max",
  "iPad Pro 13-inch (M4)",
  "iPad Pro 11-inch (M4)"
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# The name of the scheme which contains the UI Tests
scheme("App")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
